// <auto-generated />
using System;
using Coopmas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coopmas.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coopmas.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kullanici")
                        .HasColumnType("Varchar(20)");

                    b.Property<string>("Sifre")
                        .HasColumnType("Varchar(10)");

                    b.HasKey("AdminID");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Coopmas.Models.Hizmetler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dokumantasyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<string>("HizmetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ozellik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Satisİletisim")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("hizmetlers");
                });

            modelBuilder.Entity("Coopmas.Models.Urunler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dokumantasyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<string>("Ozellik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Satisİletisim")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("urunlers");
                });

            modelBuilder.Entity("Coopmas.Models.talep", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soru1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("soru2")
                        .HasColumnType("datetime2");

                    b.Property<string>("soru3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soru4")
                        .HasColumnType("int");

                    b.Property<int>("telephone")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("taleps");
                });

            modelBuilder.Entity("Coopmas.Models.İletisim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adsoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("konu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("İletisims");
                });
#pragma warning restore 612, 618
        }
    }
}
